import { useContext } from 'react'
import { DailyReportContext } from 'src/context/DailyReportContext'

const useRegisterDailyReportCompany = () => {
  const {
    storeCompanyData,
    storeIndirectWorkForceData,
    storeDirectWorkForce,
    removeDirectWorkForce,
    directWorkForceList,
    indirectWorkForceList,
    removeIndirectWorkForce,
    storeTotalIndirectWorkForce,
    storeTotalDirectWorkForce,
    storeIndirectDotationWorkForceData,
    removeIndirectDotationWorkForce,
    indirectDotationWorkForceList,
    storeDirectDotationWorkForceData,
    removeDirectDotationWorkForce,
    directDotationWorkForceList,
    storeDotationWorkfoce,
    machineryWorkForceList,
    storeMachineryWorkForce,
    removeMachineryWorkForce,
    storeEquipmentWorkForce,
    removeEquipmentWorkForce,
    equipmentWorkForceList,
    storeVehicleWorkForce,
    removeVehicleWorkForce,
    vehicleWorkForceList,
    storeComment,
    storeIncident,
    storeMachinery,
    removeMachinery,
    machineryList,
    storeEquipment,
    removeEquipment,
    equipmentList,
    storeVehicle,
    removeVehicle,
    vehicleList,
    storeActivity,
    removeActivity,
    activityList,
    storeAsarcoMachinery,
    removeAsarcoMachinery,
    asarcoMachineryList,
    storeEquipmentPlate,
    removeEquipmentPlate,
    equipmentPlateList,
  } = useContext(DailyReportContext)

  return {
    storeCompanyData,
    storeIndirectWorkForceData,
    storeDirectWorkForce,
    removeDirectWorkForce,
    directWorkForceList,
    indirectWorkForceList,
    removeIndirectWorkForce,
    storeTotalIndirectWorkForce,
    storeTotalDirectWorkForce,
    storeIndirectDotationWorkForceData,
    removeIndirectDotationWorkForce,
    indirectDotationWorkForceList,
    storeDirectDotationWorkForceData,
    removeDirectDotationWorkForce,
    directDotationWorkForceList,
    storeDotationWorkfoce,
    machineryWorkForceList,
    storeMachineryWorkForce,
    removeMachineryWorkForce,
    storeEquipmentWorkForce,
    removeEquipmentWorkForce,
    equipmentWorkForceList,
    storeVehicleWorkForce,
    removeVehicleWorkForce,
    vehicleWorkForceList,
    storeComment,
    storeIncident,
    storeMachinery,
    removeMachinery,
    machineryList,
    storeEquipment,
    removeEquipment,
    equipmentList,
    storeVehicle,
    removeVehicle,
    vehicleList,
    storeActivity,
    removeActivity,
    activityList,
    storeAsarcoMachinery,
    removeAsarcoMachinery,
    asarcoMachineryList,
    storeEquipmentPlate,
    removeEquipmentPlate,
    equipmentPlateList,
  }
}

export default useRegisterDailyReportCompany
